### ISSUE TITLE
can't "make" bme680_master

### ISSUE THREAD

**Issue by TonnyDalgaard** [paulvha/bme680#1]
Hello and thanks for your nice programs.
I love the way you solved the clockstreching issues for the scd30 on RPi. 
And that's why i want to use the bme680 program so i can run the two sensors on the same RPi. 
If i follow your description and try to create the executable : make, it says no target or makeflie.
Can you help?
A second questian, i am aiming to make a GUI that show's both sensors output.
And guess that the easiest way for a newbie is to run the scd30 and bme680 programs simultaniusly and over the same Wire and default GPIO 2 and 3.
Can that create any problems or do you have a better suggestion?

Thanks and kind regards Tonny Dalgaard

**Comment by paulvha** [comment]
HI Tony

My bad.. forgot to include the makefile. I have just uploaded it. Copy that and then run make.
As SCD30 and BME680 have different addresses they can be connected in parallel on the same wire.

regards,
Paul

**Comment by TonnyDalgaard** [comment]
Thanks for reply .
now it gives an error : 

pi@raspberrypi1:~/Geany_bme680/bme680-master $ make
gcc -Wall -Werror -c -o bme680_lib.o bme680_lib.cpp
bme680_lib.cpp: In member function 'bool rasp_BME680::performReading()':
bme680_lib.cpp:381:10: error: suggest parentheses around operand of '!' or change '&' to '&&' or '!' to '~' [-Werror=parentheses]
     if ( ! data.status & BME680_NEW_DATA_MSK)
          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
makefile:9: recipe for target 'bme680_lib.o' failed
make: *** [bme680_lib.o] Error 1

kind regards Tonny

**Comment by paulvha** [comment]
wonder what version of Debian you run: type uname -a. I have 4.9.35-v7 #1014. Just recompiled the same source without problems on my Raspberry that is running the latest version. 
I do understand however why a compiler might get confused and have an updated version on the share of bme680_lib.cpp  to solve the issue. let me know if that works

**Comment by TonnyDalgaard** [comment]
It works. thanks a lot.

**Comment by TonnyDalgaard** [comment]
Sorry forgot to say i updated, that might have been the issue.

**Comment by paulvha** [comment]
OK, nevertheless it is better to be precise in the code :-)
